version: '3'
services:
  anime-site:
    build:
      context: ./anime-site
    ports:
      - '3100:3000'
    restart: always
    networks:
      - published
      
  animevariant_com_api:
    build:
      context: ./animevariant_com_api
    ports:
      - '3200:3000'
    restart: always
    networks:
      - published

  blog-nextjs-sanity:
    build:
      context: ./blog-nextjs-sanity
    ports:
      - '3300:3000'
    restart: always
    networks:
      - published

  manga-site:
    build:
      context: ./manga-site
    ports:
      - '3400:3000'
    restart: always
    networks:
      - published

  minfuel-web:
    build:
      context: ./minfuel-web
    ports:
      - '3500:3000'
    restart: always
    networks:
      - published

  next-blog:
    build:
      context: ./next-blog
    ports:
      - '3600:3000'
    restart: always
    networks:
      - published

  altlokalt-nextjs:
    build:
      context: ./altlokalt-nextjs
    ports:
      - '3700:3000'
    restart: always
    networks:
      - published

  pocketbase-upload-maga:
    build:
      context: ./pocketbase-upload-maga
    ports:
      - '3800:3000'
    restart: always
    networks:
      - published

  simple-service-worker:
    build:
      context: ./simple-service-worker
    ports:
      - '3900:3000'
    restart: always
    networks:
      - published

networks:
  published:
